### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern-tabris#14]
@cpetrov  once your PR will be accepted, I think we could publish tern-tabris. 

What do you think about that?

**Comment by cpetrov** [comment]
@angelozerr Yes, sure!

**Comment by angelozerr** [comment]
> @angelozerr Yes, sure!

Cool! At first many thank's for your great contribution. To create and publish the release, I must do 

```
npm publish
```

But I don't know how to create a dowload in https://github.com/angelozerr/tern-tabris/releases 

Do you know if is it possible to use npm publish to publish tern-tabris and create a release entry in https://github.com/angelozerr/tern-tabris/releases autmaticly?

Thank's for your help.

**Comment by cpetrov** [comment]
@angelozerr There is a GitHub REST API for creating a release: https://developer.github.com/v3/repos/releases/#create-a-release
It seems you can't include an artifact when using this API though. 

You can hook a script using this API to package.json: https://docs.npmjs.com/misc/scripts

**Comment by angelozerr** [comment]
@cpetrov if you have time, do you think it's possible for you to write this script please?

**Comment by paulvi** [comment]
They usually `npm publish` for releases.

`npm install` is prefered as it would take care of dependencies.

For other uses it is just `git clone` (by default `master`)

You can try adding new release
https://github.com/angelozerr/tern-tabris/releases/new
just for beauty sake.

It will add code tag and give option to download as zip files.

...

Or do you want to make GitHub release right after `npm publish` automatically ?

**Comment by angelozerr** [comment]
> Or do you want to make GitHub release right after npm publish automatically ?

Yes I would like do just npm publish to publish tern-tabris + create GitHub release. But I don't know if it's possible?

**Comment by paulvi** [comment]
I guess accessing GitHub API from script would require credentials to be stored somewhere. That means that you still need to do something before doing it first time on your PC...

**Comment by cpetrov** [comment]
@angelozerr I'll experiment with this problem when I have some time

**Comment by cpetrov** [comment]
I hope PR #22 will help. You might need to 

```bash
chmod +x ./scripts/git-tag.sh
```

first though.

**Comment by angelozerr** [comment]
Done https://github.com/angelozerr/tern-tabris/releases/tag/0.1.0

Many thank's @cpetrov !
