### ISSUE TITLE
Add demo with tabris lint

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern-tabris#19]

**Comment by angelozerr** [comment]
@cpetrov I think tern-lint could interest you. Here a screenshot : 

![CodeMirror & TernTabris lint](https://github.com/angelozerr/tern-tabris/wiki/images/TernTabrisLintWithCodeMirror.png)

See my commit
https://github.com/angelozerr/tern-tabris/commit/51d2303a869695eb5c5bd6076c82532e392b921e

**Comment by cpetrov** [comment]
That's great, thank you!

Do you know if the lint CodeMirror addon could be combined with the text-hover CodeMirror addon, so that both can show tooltips which don't overlap (e.g. the lint addon has a higher priority)?

**Comment by angelozerr** [comment]
> That's great, thank you!

Glad this feature please you:)

> Do you know if the lint CodeMirror addon could be combined with the text-hover CodeMirror addon, so that both can show tooltips which don't overlap (e.g. the lint addon has a higher priority)?

I'm waiting for this comment and I'm glad that you have done it:)

The text-hover CodeMirror addon is not an official addon, it's my work (everyting which belongs to codemirror-extension is my work. See https://github.com/angelozerr/CodeMirror-XQuery

As you have seens today popup info are not shared between official lint addon and my tern-hover addon (each addons redefine their popup).

So to fix this problem, CodeMirror should provide a common mean to manage popup. I'm very busy  today to work on this topic, but if you can do some PR to CodeMirror it should be fantastic.

Just one question, have you interested with Go To Definition with Ctrl+Click (Hyperlink?)

**Comment by angelozerr** [comment]
> Do you know if the lint CodeMirror addon could be combined with the text-hover CodeMirror addon, so that both can show tooltips which don't overlap (e.g. the lint addon has a higher priority)?

@cpetrov I have fixed this problem and I have created a github project for codemirror-extension at https://github.com/angelozerr/codemirror-extension and it is know registered in the npm registry. I have remove the codemirror-extension from tern-tabris. I will do teh same thing for codemirror-javascript.

**Comment by cpetrov** [comment]
That's great! The project got much slimmer.

There is however one problem: ECMA 5 definitions are not part of the codemirror-javascript module. Should we include them in a 'defs' folder in /demos as you did in your codemirror-javascript repository?

**Comment by cpetrov** [comment]
I didn't see this was already fixed :) You can ignore my comment.
