### ISSUE TITLE
Browser demo only shows Action visibility hover snippet for visibility and enabled properties

### ISSUE THREAD

**Issue by cpetrov** [angelozerr/tern-tabris#2]
```javascript
var label = tabris.create("Label", {});
var action = tabris.create("Action", {});

var labelEnabled = label.get("enabled");
var labelVisible = label.get("visibility");
var actionEnabled = action.get("enabled");
var actionVisibility = action.get("visibility");
```

Hovering over the enabled/visibility state variables seems to always show the action visibility documentation snippet ("bool - Whether the action is visible."), although the getPropertyType() function returns the right type.

Tested with Firefox 33.1.1 and Chromium 38.0.2125.122 (290379).

**Comment by angelozerr** [comment]
Is there again this problem with your PR?

**Comment by cpetrov** [comment]
I can't reproduce the issue anymore even with the repository state of the 1st of December (always the generic bool doc: `bool — The Boolean object is an object wrapper for a boolean value. [docs]` gets shown) so I'm closing the issue.
