### ISSUE TITLE
Include events and links to tabris.js object definitions

### ISSUE THREAD

**Issue by cpetrov** [angelozerr/tern-tabris#3]
We would also need to include additional data about links and events in the Tern defs, e.g. supported events + descriptions and links to relevant tabris.js objects examples and snippets. Should this be part of the "!doc"?

**Comment by angelozerr** [comment]
!doc is the only mean to add documentation with ternjs

**Comment by cpetrov** [comment]
@angelozerr thanks! Event support also got introduced by 68ac346, so I'm closing this issue.
