### ISSUE TITLE
get() autocompletion throws exception

### ISSUE THREAD

**Issue by cpetrov** [angelozerr/tern-tabris#36]
@eb2f2c6 seems to have introduced a regression. get() autocompletion throws an error:

```
TypeError: null is not an object (evaluating 'propertyType.isEmpty')
```

To reproduce:

```javascript
tabris.create("Button").get("")
```

**Comment by cpetrov** [comment]
@angelozerr: Thank you for this quick fix!

**Comment by angelozerr** [comment]
You aer welcome @cpetrov! Sorry for my mistake, I'm sorry, I'm a little exhaustive -(
